# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(18171A)
$foreground = rgb(F4EEE7)
$color0 = rgb(3F3E41)
$color1 = rgb(201D27)
$color2 = rgb(483C4D)
$color3 = rgb(524855)
$color4 = rgb(7D6D7D)
$color5 = rgb(857383)
$color6 = rgb(A79A8B)
$color7 = rgb(E6DED4)
$color8 = rgb(A19B94)
$color9 = rgb(2B2635)
$color10 = rgb(605067)
$color11 = rgb(6E6072)
$color12 = rgb(A791A6)
$color13 = rgb(B199AF)
$color14 = rgb(DFCDB9)
$color15 = rgb(E6DED4)
