$background = rgb(030005)
$foreground = rgb(EFEAF4)
$color0 = rgb(161317)
$color1 = rgb(483C4D)
$color2 = rgb(4D4153)
$color3 = rgb(6D6275)
$color4 = rgb(796476)
$color5 = rgb(988DA2)
$color6 = rgb(9E92A8)
$color7 = rgb(E0D9E7)
$color8 = rgb(9D98A2)
$color9 = rgb(605067)
$color10 = rgb(67576F)
$color11 = rgb(92829C)
$color12 = rgb(A1869D)
$color13 = rgb(CBBCD8)
$color14 = rgb(D2C3E0)
$color15 = rgb(E0D9E7)
