$background = rgb(2C2424)
$foreground = rgb(F3E7E1)
$color0 = rgb(423939)
$color1 = rgb(8A6B66)
$color2 = rgb(91736D)
$color3 = rgb(977B73)
$color4 = rgb(9E8379)
$color5 = rgb(A58C80)
$color6 = rgb(A58C80)
$color7 = rgb(E5D4CC)
$color8 = rgb(A0948F)
$color9 = rgb(B88E89)
$color10 = rgb(C19991)
$color11 = rgb(CAA499)
$color12 = rgb(D3AFA2)
$color13 = rgb(DCBAAA)
$color14 = rgb(DCBAAA)
$color15 = rgb(E5D4CC)
